PROJECT_DIR=.

CFLAGS=-I${PROJECT_DIR}/include/
CC=gcc
CXX=g++ -std=c++11
LDFLAGS=

# Using OpenCV for Visualization
# 0 for off 1 for on 
OPENCV=1
ifeq ($(OPENCV), 0)
	LDFLAGS+=  `pkg-config --libs opencv4`
	CFLAGS+= -DOPENCV=1 `pkg-config --cflags opencv4`
endif

SRC_DIR=${PROJECT_DIR}/src
OBJ_DIR=${PROJECT_DIR}/objs


all: run

run: compile

compile: main


main: ${OBJ_DIR}/linked_list.o ${OBJ_DIR}/graph.o ${OBJ_DIR}/queue.o ${OBJ_DIR}/main.o
	${CXX} ${CFLAGS} $^ ${LDFLAGS} -o bin/$@ 


${OBJ_DIR}/%.o: ${SRC_DIR}/%.cpp
	${CXX} $(CFLAGS) -c $< -o $@

